web:
  enable_proxy: true
  proxy_header: X-Forwarded-For
  trusted_proxy:
    - 127.0.0.1
  bind: 0.0.0.0
  port: '8080'
gateway:
  xendit:
    label: xendit
    api_key: YOUR_GATEWAY_API_KEY
    admin_token: []
    admin_ip: []
    webhook_tokens:
      - 'YOUR_WEBHOOK_TOKEN'
    callback_urls:
      - 'YOUR_CALLBACK_URL'
  paypal:
    label: paypal
    api_key: YOUR_GATEWAY_API_KEY
    admin_token: []
    admin_ip: []
    webhook_tokens:
      - 'YOUR_WEBHOOK_TOKEN'
    callback_urls:
      - 'YOUR_CALLBACK_URL'